version: "2"
services:
  catalogue_api:
    build: . 
    depends_on:
      - miMongodb
    ports:
      - "3000:3000"
    links:
      - miMongodb
  miMongodb:
    image: mongo:3.6.2
    volumes:
      - c:/Temp/data/catalogue_db:/data/catalogue_db
    ports:
      - "27017:27017" 
